project:
  type: website
  output-dir: docs

website:
  title: "UCSB SIAM Student Chapter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ChapterReps.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



