project:
  type: website
  output-dir: docs

website:
  title: "UCSB SIAM Student Chapter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Schedule of Events.qmd
      - ChapterReps.qmd
      - Join Chapter.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



